name = "raintree"
main = "src/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[[durable_objects.bindings]]
name = "STOCK_ROOM"
class_name = "StockRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["StockRoom"]

[assets]
binding = "ASSETS"
directory = "./src/public"

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true
