/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StockHistoryRouteImport } from './routes/stock-history'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OpnameRouteImport } from './routes/opname'
import { Route as ImportRouteImport } from './routes/import'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'

const StockHistoryRoute = StockHistoryRouteImport.update({
  id: '/stock-history',
  path: '/stock-history',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OpnameRoute = OpnameRouteImport.update({
  id: '/opname',
  path: '/opname',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/opname': typeof OpnameRoute
  '/products': typeof ProductsRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/sign-up': typeof SignUpRoute
  '/stock-history': typeof StockHistoryRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/opname': typeof OpnameRoute
  '/products': typeof ProductsRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/sign-up': typeof SignUpRoute
  '/stock-history': typeof StockHistoryRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/opname': typeof OpnameRoute
  '/products': typeof ProductsRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/sign-up': typeof SignUpRoute
  '/stock-history': typeof StockHistoryRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/import'
    | '/opname'
    | '/products'
    | '/review'
    | '/settings'
    | '/sign-up'
    | '/stock-history'
    | '/api/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/import'
    | '/opname'
    | '/products'
    | '/review'
    | '/settings'
    | '/sign-up'
    | '/stock-history'
    | '/api/$'
  id:
    | '__root__'
    | '/'
    | '/import'
    | '/opname'
    | '/products'
    | '/review'
    | '/settings'
    | '/sign-up'
    | '/stock-history'
    | '/api/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportRoute: typeof ImportRoute
  OpnameRoute: typeof OpnameRoute
  ProductsRoute: typeof ProductsRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  SignUpRoute: typeof SignUpRoute
  StockHistoryRoute: typeof StockHistoryRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stock-history': {
      id: '/stock-history'
      path: '/stock-history'
      fullPath: '/stock-history'
      preLoaderRoute: typeof StockHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opname': {
      id: '/opname'
      path: '/opname'
      fullPath: '/opname'
      preLoaderRoute: typeof OpnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportRoute: ImportRoute,
  OpnameRoute: OpnameRoute,
  ProductsRoute: ProductsRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  SignUpRoute: SignUpRoute,
  StockHistoryRoute: StockHistoryRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
